-- 코드를 입력하세요
SELECT I.REST_ID, REST_NAME,FOOD_TYPE, FAVORITES, ADDRESS, ROUND(SCORE,2) AS SCORE
FROM REST_INFO AS I
JOIN (SELECT REST_ID, AVG(REVIEW_SCORE) AS SCORE
     FROM REST_REVIEW
     GROUP BY REST_ID) AS R ON I.REST_ID = R.REST_ID
WHERE I.ADDRESS LIKE "서울%"
ORDER BY SCORE DESC, FAVORITES DESC