-- 코드를 입력하세요
SELECT DISTINCT HISTORY_ID, ROUND(DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE)+1) * 
                                (CASE WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 < 7 THEN 1
                                 WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 <30 THEN 0.95
                                 WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 < 90 THEN 0.92
                                 ELSE 0.85 END)) AS FEE

FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
JOIN CAR_RENTAL_COMPANY_CAR AS C ON C.CAR_ID = H.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE = '트럭'        
ORDER BY FEE DESC, HISTORY_ID DESC