-- 코드를 입력하세요

-- 코드를 입력하세요

SELECT P.MEMBER_NAME, R.REVIEW_TEXT, R.REVIEW_DATE
FROM REST_REVIEW AS R
JOIN MEMBER_PROFILE AS P ON R.MEMBER_ID = P.MEMBER_ID
WHERE R.MEMBER_ID = (SELECT R.MEMBER_ID
                    FROM REST_REVIEW AS R
                    JOIN MEMBER_PROFILE AS P ON R.MEMBER_ID = P.MEMBER_ID
                    GROUP BY P.MEMBER_ID
                    ORDER BY COUNT(*) DESC
                    LIMIT 1)
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT

